name: Build Win32 JNI Wrapper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [msvc]
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with MSVC
        if: matrix.compiler == 'msvc'
        shell: cmd
        run: |
          echo "Building with MSVC..."
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          
          cl /LD /nologo ^
             /I"%JAVA_HOME%\include" ^
             /I"%JAVA_HOME%\include\win32" ^
             mmfplayer_native_jni.c ^
             /Femmfplayer_native_msvc.dll ^
             /link /DLL /NOLOGO /OUT:mmfplayer.dll
          
          if %errorlevel% neq 0 (
            echo "MSVC compilation failed"
            exit /b 1
          )
          echo "MSVC build successful"

      - name: Upload MSVC Artifact
        if: matrix.compiler == 'msvc'
        uses: actions/upload-artifact@v4
        with:
          name: mmfplayer-native-msvc
          path: mmfplayer.dll
          retention-days: 30
