name: Build Win32 JNI Wrapper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup MSYS2 MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: mingw-w64-i686-toolchain

      - name: Build JNI DLL
        shell: msys2 {0}
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        run: |
          i686-w64-mingw32-gcc -m32 -shared -o mmfplayer_native.dll mmfplayer_native_jni.c -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/win32" -Wl,--add-stdcall-alias

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mmfplayer_native-dll
          path: mmfplayer_native.dll
